# Generated by Django 5.2 on 2025-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.TextField(default="N/A"),
        ),
    ]
