# Generated by Django 5.2 on 2025-06-08 19:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("payment", models.CharField(max_length=50)),
                ("total", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Đang xử lý", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Shoes",
            fields=[
                ("sku", models.AutoField(primary_key=True, serialize=False)),
                ("shoe_name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("color_general", models.TextField(blank=True, null=True)),
                ("original_price", models.IntegerField(blank=True, null=True)),
                ("brand", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "myapp_shoes",
            },
        ),
        migrations.CreateModel(
            name="ShoeImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        db_column="sku",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.shoes",
                    ),
                ),
            ],
            options={
                "db_table": "myapp_shoeimages",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="myapp.order",
                    ),
                ),
                (
                    "shoe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.shoes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvailableSizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.TextField(blank=True, null=True)),
                ("in_stock", models.IntegerField(blank=True, null=True)),
                (
                    "sku",
                    models.ForeignKey(
                        db_column="sku",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.shoes",
                    ),
                ),
            ],
            options={
                "db_table": "myapp_availablesizes",
            },
        ),
    ]
