# Generated by Django 5.2 on 2025-06-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="availablesizes",
            table=None,
        ),
        migrations.AlterModelTable(
            name="shoeimages",
            table=None,
        ),
        migrations.AlterModelTable(
            name="shoes",
            table=None,
        ),
    ]
